name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'clients/typescript/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'clients/typescript/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    defaults:
      run:
        working-directory: clients/typescript

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: clients/typescript/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check types
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
        continue-on-error: true # Tests not implemented yet

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: clients/typescript

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: clients/typescript/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true # ESLint not fully configured yet

